### ISSUE TITLE
zeroSSL certificate not working

### ISSUE THREAD

**Issue by woohwan** [quay/openshift-mirror-registry#31]
$ openshift-mirror-registry install --initPassword whsy0805 --quayHostname registry.steve-ml.net --sslCert ./quay_certs/ssl.cert --sslKey ./quay_certs/ssl.key --verbose

INFO[2021-12-23 17:53:08] Detected an installation to localhost
DEBU[2021-12-23 17:53:08] Running command: sudo podman run --rm --interactive --tty --workdir /runner/project --net host -v /root/Downloads/registry/image-archive.tar:/runner/image-archive.tar-v /root/work/quay_certs/ssl.cert:/runner/certs/quay.cert:Z -v /root/work/quay_certs/ssl.key:/runner/certs/quay.key:Z -v /root/.ssh/quay_installer:/runner/env/ssh_key -e RUNNER_OMIT_EVENTS=False -e RUNNER_ONLY_FAILED_EVENTS=False -e ANSIBLE_HOST_KEY_CHECKING=False -e ANSIBLE_CONFIG=/runner/project/ansible.cfg --quiet --name ansible_runner_instance quay.io/quay/openshift-mirror-registry-ee ansible-playbook -i root@localhost, --private-key /runner/env/ssh_key -e "init_password=whsy0805 quay_image=registry.redhat.io/quay/quay-rhel8:v3.6.1 redis_image=registry.redhat.io/rhel8/redis-6:1-25 postgres_image=registry.redhat.io/rhel8/postgresql-10:1-161 quay_hostname=registry.steve-ml.net:8443 local_install=true quay_root=/etc/quay-install" install_mirror_appliance.yml
Error: invalid reference format

and 
I followd the site
https://access.redhat.com/documentation/en-us/red_hat_quay/2.9/html/manage_red_hat_quay/using-ssl-to-protect-quay

same prbolem occurred.

**Comment by HammerMeetNail** [comment]
@woohwan Thanks for raising this. Can you provide a little more information?

1. What OS and Podman version are being used?
2. Does the command work if you omit the `--sslCert` and `--sslKey` options?

**Comment by HammerMeetNail** [comment]
See https://github.com/quay/openshift-mirror-registry/releases/tag/1.0.0-RC2 for the new release with patch

**Comment by woohwan** [comment]
Thanks. it works.
